#!/bin/sh

# Allow the database to come up properly
# NOTE: we could be better about how we do this...
sleep 3600

while true; do
  echo "Backing up database."
  /conf/backup-command
  # Run once a week by default
  sleep ${DB_BACKUP_INTERVAL:-604800}
done
