services:
  db_server:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  storage:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=test
      - MINIO_SECRET_KEY=test_secret
  db_backup:
    build: .
    command: "echo"
    environment:
      - S3_ENDPOINT=http://storage:9000
      - S3_ACCESS_KEY=test
      - S3_SECRET_KEY=test_secret
      - S3_BACKUP_BUCKET=test_backup
      - DB_NAME=test_database
      - DB_HOST=db_server