services:
  db_server:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  storage:
    build:
      context: .
      dockerfile: Dockerfile.minio-test
    entrypoint: ""
    command: bash -c 'mkdir -p /data/test-bucket && minio server /data'
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=test
      - MINIO_SECRET_KEY=test_secret
  db_backup:
    build: .
    command: "echo"
    environment:
      - S3_ENDPOINT=http://storage:9000
      - S3_ACCESS_KEY=test
      - S3_SECRET_KEY=test_secret
      - S3_BACKUP_BUCKET
      - DB_BACKUP_PREFIX
      - DB_NAME
      - PGHOST=db_server