#!/usr/bin/env bash
# Mock an S3 server

export COMPOSE_FILE="docker-compose.test.yaml"

docker compose build
docker compose up -d

while ! docker compose exec db_server pg_isready ; do
  echo "Waiting for PostgreSQL server to be ready..."
  sleep 1
done

docker compose exec db_server psql -U postgres -p 5432 test_database -c \
"CREATE TABLE test_table (id serial PRIMARY KEY, name text); \
INSERT INTO test_table (name) VALUES ('test');"

echo "Created test database"

docker compose run db_backup backup-db
docker compose rm -f --volumes