#!/usr/bin/env bash

# A test suite for database backup scripts
# TODO: we might want to rewrite this in python for clarity and added features.
# But the current shell version is fine for now.

export COMPOSE_FILE="docker-compose.test.yaml"
export S3_BACKUP_BUCKET="test-bucket"

docker compose up --build --remove-orphans --force-recreate -d

while ! docker compose exec db_server pg_isready ; do
  echo "Waiting for PostgreSQL server to be ready..."
  sleep 1
done

docker compose exec db_server createdb test_database

docker compose exec db_server psql -p 5432 test_database -c \
"CREATE TABLE test_table (id serial PRIMARY KEY, name text); \
INSERT INTO test_table (name) VALUES ('test');"

echo "Created test database"

echo "-> Testing basic backup"

docker compose run db_backup backup-db

file_list=$(docker compose exec storage ls /data/test-bucket)

docker compose down
docker compose rm -f --volumes

exit_status=0
if [ -z "$file_list" ]; then
  echo "No files found in S3 bucket."
  exit_status=1
else
  echo $file_list
  echo "Backup file saved successfully!"
fi

if (( $exit_status )); then
  echo "Tests failed!"
  exit $exit_status
else
  echo "Tests passed!"
fi
